from dataclasses import dataclass

from docx import Document
from PIL import Image

from utils.report_generator import WordReportGenerator


@dataclass
class ReportSection:
    section_name: str
    analysis_widgets: list


class ReportController:
    def __init__(self, image_path):
        self.image_path = image_path

    def getPlotImage(self):
        return self.image_path

    def getStatsTableData(self):
        return [["Mean", "1.23"], ["Std", "0.04"]]


class ReportAnalysis:
    analysis_title = "Moisture Trend"
    analysis_name = "Time Domain"
    info_string = "generated by test"
    report_layout = "stats-right"
    image_width_mm = None

    def __init__(self, image_path):
        self.controller = ReportController(image_path)

    def get_channel_text(self):
        return "Moisture"


def test_word_report_contains_sections_analysis_images_and_stats(tmp_path, monkeypatch):
    monkeypatch.setattr("settings.REPORT_ENABLE_ANALYSIS_TITLE", True)
    monkeypatch.setattr("settings.REPORT_SECTION_NEWPAGE", False)

    header_image_path = tmp_path / "header.png"
    plot_image_path = tmp_path / "plot.png"
    Image.new("RGB", (32, 16), color=(180, 30, 60)).save(header_image_path)
    Image.new("RGB", (64, 32), color=(20, 120, 200)).save(plot_image_path)

    output_path = tmp_path / "report.docx"
    report_data = {
        "title": "Regression Report",
        "subtitle": "paper machine 1",
        "additional_info": "unit test",
        "header_image_path": str(header_image_path),
        "sections": [
            ReportSection(
                "MD Analysis",
                [ReportAnalysis(str(plot_image_path))],
            )
        ],
        "window_type": "MD",
    }

    WordReportGenerator(report_data).generate(output_path)

    doc = Document(output_path)
    body_text = "\n".join(paragraph.text for paragraph in doc.paragraphs)
    document_text = "\n".join(node.text for node in doc.element.iter() if node.text)
    image_rels = [
        rel for rel in doc.part.rels.values() if "image" in rel.reltype
    ]

    assert "MD Analysis" in body_text
    assert "Moisture Trend" in body_text
    assert "Mean" in document_text
    assert "1.23" in document_text
    assert image_rels
